import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import "./globals.css";
import { Raleway} from 'next/font/google';
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const raleway = Raleway({
  subsets: ['latin']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en"  className={`${raleway.className}`}>
        <body className="bg-gray-50">
          {children}  
        </body>
      </html>
    </ClerkProvider>
  );
}
